# Generated by Django 5.0.6 on 2024-08-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_national_code'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
