# Generated by Django 5.0.6 on 2024-08-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
