# Generated by Django 5.0.6 on 2024-08-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
