# Generated by Django 5.0.6 on 2024-08-26 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complex', '0002_alter_session_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_number', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('reserve_note', models.CharField(blank=True, max_length=100, null=True)),
                ('reserve_total', models.IntegerField()),
                ('status', models.CharField(choices=[('در انتظار پرداخت', 'در انتظار پرداخت'), ('تایید شده', 'تایید شده'), ('کنسل شده', 'کنسل شده'), ('تاریخ پرداخت گدشته', 'تاریخ پرداخت گذشته')], default='در انتظار پرداخت', max_length=25)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('is_reserved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RESERVES', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=10)),
                ('pay_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reserve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payment.reserve')),
            ],
        ),
    ]
