# Generated by Django 5.0.6 on 2024-06-21 16:39

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('cat_image', models.ImageField(blank=True, upload_to='photos/category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complex_name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='complex_name', unique=True)),
                ('complex_description', models.TextField(blank=True, max_length=700)),
                ('complex_img', models.ImageField(blank=True, upload_to='photos/complexes')),
                ('area', models.IntegerField()),
                ('price_variation', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('Address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=255)),
                ('neighborhood', models.CharField(max_length=255)),
                ('guards_count', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('session_long', models.CharField(max_length=255)),
                ('close_days', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='complex.category')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('session_price', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('is_reserved', models.BooleanField(default=False)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.complex')),
            ],
        ),
    ]
